# Generated by Django 4.0.1 on 2022-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='img_name',
            field=models.CharField(default='images/default.webp', max_length=200),
            preserve_default=False,
        ),
    ]
