# Generated by Django 4.0.1 on 2022-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
