# Generated by Django 4.0.1 on 2022-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_name',
            new_name='img_name_big',
        ),
        migrations.AddField(
            model_name='post',
            name='img_name_small',
            field=models.CharField(default='shit', max_length=200),
            preserve_default=False,
        ),
    ]
